# Generated by Django 3.0.5 on 2020-04-11 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_remove_organization_agent'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='makorganization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='issue.Organization'),
        ),
    ]
