# Generated by Django 3.0.5 on 2020-04-11 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0003_organization_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='agent',
        ),
        migrations.AddField(
            model_name='organization',
            name='agent',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
