# Generated by Django 3.0.5 on 2020-04-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_auto_20200411_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='agent',
        ),
    ]
