# Generated by Django 3.0.5 on 2020-04-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_remove_organization_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btissues',
            name='satisfaction_remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
